version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11

workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          test_results_path: build/reports/tests
          reports_path: build/reports/
  checkout-run_task:
    jobs:
      - gradle/run:
          command: build -x test

jobs:
