version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11
  docker: circleci/docker@0.5.13

workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          test_results_path: build/reports/tests
          reports_path: build/reports/
      - gradle/run:
          command: build -x test
      - docker/publish:
          deploy: false
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME

jobs:
