version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11
  docker: circleci/docker@0.5.13

workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          test_results_path: build/reports/tests
          reports_path: build/reports/
      - build_jar
      - build_docker_image:
          requires:
            - build_jar

jobs:
  build_jar:
    executor: docker/machine
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Run Task
                command: ./gradlew build -x test
            - persist_to_workspace:
                root: "~"
                paths:
                  - build/libs/gs-spring-boot-0.1.0.jar

  build_docker_image:
    executor: docker/machine
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy build artifacts from workspace
          command: cp /tmp/workspace/build .
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
